name: MOBAN_BUILD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache CUDA Toolkit
        uses: actions/cache@v3
        with:
          path: /usr/local/cuda
          key: ${{ runner.os }}-cuda-11.2
      - name: Install CUDA Toolkit
        run: |
          sudo apt-get install -y cuda-toolkit-11-2
          echo "CUDAToolkit_ROOT=/usr/local/cuda" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/local/cuda/bin" >> $GITHUB_ENV
      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          make build-tests && make check-tests