name: MOBAN_BUILD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # 关键：递归初始化所有子模块
          fetch-depth: 0  # 获取完整历史（某些子模块需要）
      - name: Update submodules
        run: |
           git submodule update --init --recursive
           echo "Submodules updated:"
           git submodule status
      - name: Set up CUDA repository
        run: |
          # 下载并配置 CUDA 软件源
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
          sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
          sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
          sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /"
      - name: Cache CUDA Toolkit
        uses: actions/cache@v3
        with:
          path: /usr/local/cuda
          key: ${{ runner.os }}-cuda-12.5
      - name: Install CUDA Toolkit
        run: |
          sudo apt-get update
          sudo apt-get install -y cuda-toolkit-12-5
          echo "CUDAToolkit_ROOT=/usr/local/cuda" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/local/cuda/bin" >> $GITHUB_ENV
      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CUDA_ARCHITECTURES=75 ..
          make
          make build-tests && make check-tests